import Link from 'next/link'
import { ArrowRight, Bot, Target, Briefcase, Activity } from 'lucide-react'

export default function LandingPage() {
  return (
    <div className="flex flex-col items-center justify-center min-h-[80vh] text-center animate-in fade-in slide-in-from-bottom-8 duration-700">
      
      <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-violet-500/10 border border-violet-500/20 text-violet-300 text-sm mb-8">
        <Bot size={14} />
        <span>Powered by 6 Specialized AI Agents</span>
      </div>

      <h1 className="text-5xl md:text-7xl font-extrabold text-white tracking-tight max-w-4xl">
        The Ultimate <span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-400 to-fuchsia-500">AI Career</span> Operating System
      </h1>
      
      <p className="mt-6 text-xl text-gray-400 max-w-2xl">
        Not just a chatbot. A multi-agent ecosystem that analyzes your resume, builds a roadmap, conducts mock interviews, and finds your perfect internship.
      </p>

      <div className="mt-10 flex gap-4">
        <Link href="/login" className="px-8 py-4 bg-violet-600 hover:bg-violet-700 text-white rounded-xl font-semibold flex items-center gap-2 transition shadow-lg shadow-violet-600/20">
          Get Started <ArrowRight size={18} />
        </Link>
        <a href="https://github.com" target="_blank" className="px-8 py-4 bg-white/5 hover:bg-white/10 border border-white/10 text-white rounded-xl font-semibold transition">
          View Demo Video
        </a>
      </div>

      <div className="mt-24 grid grid-cols-1 md:grid-cols-3 gap-8 w-full max-w-5xl text-left">
        <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
          <div className="w-12 h-12 bg-blue-500/10 rounded-xl flex items-center justify-center mb-4 border border-blue-500/20">
            <Activity className="text-blue-400" />
          </div>
          <h3 className="text-xl font-semibold text-white mb-2">Resume Intelligence</h3>
          <p className="text-gray-400">Deep ATS analysis and role-specific skill gap detection powered by our Analyzer Agent.</p>
        </div>
        <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
          <div className="w-12 h-12 bg-emerald-500/10 rounded-xl flex items-center justify-center mb-4 border border-emerald-500/20">
            <Target className="text-emerald-400" />
          </div>
          <h3 className="text-xl font-semibold text-white mb-2">Adaptive Roadmaps</h3>
          <p className="text-gray-400">Week-by-week personalized career planners generated by combining your goal and current skills.</p>
        </div>
        <div className="p-6 rounded-2xl bg-white/5 border border-white/10">
          <div className="w-12 h-12 bg-fuchsia-500/10 rounded-xl flex items-center justify-center mb-4 border border-fuchsia-500/20">
            <Briefcase className="text-fuchsia-400" />
          </div>
          <h3 className="text-xl font-semibold text-white mb-2">Smart Matching</h3>
          <p className="text-gray-400">Stop scrolling. Our Internship Matcher evaluates your exact fit for 25+ top tech roles.</p>
        </div>
      </div>

    </div>
  )
}
